export { default as UiButton } from './UiButton.vue';
export { default as UiInput } from './UiInput.vue';
export { default as UiTextarea } from './UiTextarea.vue';
export { default as UiSelect } from './UiSelect.vue';
export type { SelectItem } from './UiSelect.vue';
export { default as UiSwitch } from './UiSwitch.vue';
export { default as UiTooltip } from './UiTooltip.vue';
export { default as UiField } from './UiField.vue';
export { default as UiContainer } from './UiContainer.vue';
export { default as UiRow } from './UiRow.vue';
export { default as UiCol } from './UiCol.vue';
export { default as UiSpacer } from './UiSpacer.vue';
export { default as UiForm } from './UiForm.vue';
export { default as UiFormSection } from './UiFormSection.vue';
export { default as UiFormActions } from './UiFormActions.vue';
export type { GridSize, LayoutDensity, FieldLayout } from './layout';
export type { ControlSizing } from './control-sizing';
export { default as UiTabs } from './UiTabs.vue';
export { default as UiTab } from './UiTab.vue';
export { default as UiTabsWindow } from './UiTabsWindow.vue';
export { default as UiTabsWindowItem } from './UiTabsWindowItem.vue';
export type { TabValue, TabItem } from './tabs';
export { default as UiTabPanel } from './UiTabPanel.vue';
export { default as UiDialog } from './UiDialog.vue';
export { default as UiCollapse } from './UiCollapse.vue';
export { default as UiSnackbarHost } from './UiSnackbarHost.vue';
export { default as UiCard } from './UiCard.vue';
export { default as UiScrollArea } from './UiScrollArea.vue';
export { vRipple } from './ripple';
export type { RippleOptions } from './ripple';
export { snackbar } from './snackbar';
export type { SnackbarOptions, SnackbarPosition, SnackbarTone } from './snackbar';
export { default as UiCodeBlock } from './UiCodeBlock.vue';
export { default as UiTable } from './UiTable.vue';
export { default as UiDataTableServer } from './UiDataTableServer.vue';
export { default as UiPagination } from './UiPagination.vue';
export type { TableHeader, TableSort, TableOptions } from './table';

export { default as UiIcon } from '../components/Icon.vue';
export { registerIcons } from './icons';

export { default as UiActivity } from './UiActivity.vue';
export { default as UiDiff } from './UiDiff.vue';
export { default as UiMarkdown } from './UiMarkdown.vue';
export { setClipboardWriter, writeClipboard } from './clipboard';
export { default as UiFileChanges } from './UiFileChanges.vue';
export type { FileChangeItem } from './UiFileChanges.vue';
export { lineDiff } from './line-diff';
export { default as UiMessageActions } from './UiMessageActions.vue';
export type { MessageActionItem } from './UiMessageActions.vue';

export { default as UiUsageMeter } from './UiUsageMeter.vue';
export type { UsageSegment } from './UiUsageMeter.vue';

export { setLocale, getLocale, uiLocale, uiText } from './locale';
export type { UiLocale, UiMessageKey } from './locale';

export { default as UiBadge } from './UiBadge.vue';
export { default as UiAlert } from './UiAlert.vue';
export { default as UiSpinner } from './UiSpinner.vue';
export { default as UiMenu } from './UiMenu.vue';
export { default as UiMenuItem } from './UiMenuItem.vue';
export type { MenuPlacement } from './menu';
export { default as UiConfirmHost } from './UiConfirmHost.vue';
export { confirmDialog } from './confirm';
export type { ConfirmOptions } from './confirm';

export { default as UiCheckbox } from './UiCheckbox.vue';
export { default as UiRadio } from './UiRadio.vue';
export { default as UiProgress } from './UiProgress.vue';
export { default as UiCopyButton } from './UiCopyButton.vue';
export { default as UiColorSwatches } from './UiColorSwatches.vue';
export type { ColorSwatch } from './UiColorSwatches.vue';
export type { ValidationRule, ValidateOn, ValidationResult } from './validation';
export type { FormControlProps, FormValidationResult, FormError } from './form';

export { default as UiCascader } from './UiCascader.vue';
export type { CascaderItem, CascaderValue } from './cascader';
export { default as UiThemeProvider } from './UiThemeProvider.vue';
export { createUiTheme, useUiTheme } from './theme';
export type { UiThemeDefinition, UiResolvedTheme, UiThemeOptions, UiThemeInstance, UiThemeTransition } from './theme';
export { createUI } from './plugin';
export type { UIOptions } from './plugin';
export type { SlideGroupProps } from './slide-group';
export type { SnackbarProps, SnackbarMessage, SnackbarDismissReason } from './snackbar-props';
export { useDefaults } from './defaults';
export type { UIDefaults } from './defaults';
export { useDisplay, createDisplay, displayThresholds } from './display';
export type { DisplayOptions, DisplayBreakpoint, UIDisplay } from './display';
export { useLocale, createLocale } from './locale-context';
export type { LocaleOptions } from './locale-context';
export { useRules, createRules } from './rules';
export { useGoTo } from './goto';
export { vClickOutside, vIntersect, vMutate, vResize, vScroll, vTouch, vTooltip } from './directives';

// Canonical u- component exports (generated by scripts/sync-components.mjs).
export { default as UButton } from './UiButton.vue';
export { default as UTextField } from './UiInput.vue';
export { default as UTextarea } from './UiTextarea.vue';
export { default as USelect } from './UiSelect.vue';
export { default as USwitch } from './UiSwitch.vue';
export { default as UTooltip } from './UiTooltip.vue';
export { default as UField } from './UiField.vue';
export { default as UContainer } from './UiContainer.vue';
export { default as URow } from './UiRow.vue';
export { default as UCol } from './UiCol.vue';
export { default as USpacer } from './UiSpacer.vue';
export { default as UForm } from './UiForm.vue';
export { default as UFormSection } from './UiFormSection.vue';
export { default as UFormActions } from './UiFormActions.vue';
export { default as UTabs } from './UiTabs.vue';
export { default as UTab } from './UiTab.vue';
export { default as UTabsWindow } from './UiTabsWindow.vue';
export { default as UTabsWindowItem } from './UiTabsWindowItem.vue';
export { default as UTabPanel } from './UiTabPanel.vue';
export { default as UDialog } from './UiDialog.vue';
export { default as UCollapse } from './UiCollapse.vue';
export { default as USnackbarHost } from './UiSnackbarHost.vue';
export { default as UCard } from './UiCard.vue';
export { default as UScrollArea } from './UiScrollArea.vue';
export { default as UCodeBlock } from './UiCodeBlock.vue';
export { default as UTable } from './UiTable.vue';
export { default as UDataTableServer } from './UiDataTableServer.vue';
export { default as UPagination } from './UiPagination.vue';
export { default as UIcon } from '../components/Icon.vue';
export { default as UActivity } from './UiActivity.vue';
export { default as UDiff } from './UiDiff.vue';
export { default as UMarkdown } from './UiMarkdown.vue';
export { default as UFileChanges } from './UiFileChanges.vue';
export { default as UMessageActions } from './UiMessageActions.vue';
export { default as UUsageMeter } from './UiUsageMeter.vue';
export { default as UChip } from './UChip.vue';
export { default as UAlert } from './UiAlert.vue';
export { default as USpinner } from './UiSpinner.vue';
export { default as UMenu } from './UiMenu.vue';
export { default as UMenuItem } from './UiMenuItem.vue';
export { default as UConfirmHost } from './UiConfirmHost.vue';
export { default as UCheckbox } from './UiCheckbox.vue';
export { default as URadio } from './UiRadio.vue';
export { default as UProgress } from './UiProgress.vue';
export { default as UCopyButton } from './UiCopyButton.vue';
export { default as UColorSwatches } from './UiColorSwatches.vue';
export { default as UCascader } from './UiCascader.vue';
export { default as UThemeProvider } from './UiThemeProvider.vue';
export { default as UApp } from './UApp.vue';
export { default as UAppBar } from './UAppBar.vue';
export { default as UAppBarTitle } from './UAppBarTitle.vue';
export { default as UAutocomplete } from './UAutocomplete.vue';
export { default as UAvatar } from './UAvatar.vue';
export { default as UBadge } from './UBadge.vue';
export { default as UBanner } from './UBanner.vue';
export { default as UBottomNavigation } from './UBottomNavigation.vue';
export { default as UBottomSheet } from './UBottomSheet.vue';
export { default as UBreadcrumbs } from './UBreadcrumbs.vue';
export { default as UBreadcrumbsDivider } from './UBreadcrumbsDivider.vue';
export { default as UBreadcrumbsItem } from './UBreadcrumbsItem.vue';
export { default as UBtnGroup } from './UBtnGroup.vue';
export { default as UBtnToggle } from './UBtnToggle.vue';
export { default as UCalendar } from './UCalendar.vue';
export { default as UCarousel } from './UCarousel.vue';
export { default as UCarouselItem } from './UCarouselItem.vue';
export { default as UCheckboxGroup } from './UCheckboxGroup.vue';
export { default as UChipGroup } from './UChipGroup.vue';
export { default as UCode } from './UCode.vue';
export { default as UColorInput } from './UColorInput.vue';
export { default as UColorPicker } from './UColorPicker.vue';
export { default as UCombobox } from './UCombobox.vue';
export { default as UConfirmEdit } from './UConfirmEdit.vue';
export { default as UCounter } from './UCounter.vue';
export { default as UDataIterator } from './UDataIterator.vue';
export { default as UDataTable } from './UDataTable.vue';
export { default as UDataTableVirtual } from './UDataTableVirtual.vue';
export { default as UDateInput } from './UDateInput.vue';
export { default as UDatePicker } from './UDatePicker.vue';
export { default as UDefaultsProvider } from './UDefaultsProvider.vue';
export { default as UDivider } from './UDivider.vue';
export { default as UEmptyState } from './UEmptyState.vue';
export { default as UExpansionPanel } from './UExpansionPanel.vue';
export { default as UExpansionPanelText } from './UExpansionPanelText.vue';
export { default as UExpansionPanelTitle } from './UExpansionPanelTitle.vue';
export { default as UExpansionPanels } from './UExpansionPanels.vue';
export { default as UFab } from './UFab.vue';
export { default as UFileInput } from './UFileInput.vue';
export { default as UFileUpload } from './UFileUpload.vue';
export { default as UFooter } from './UFooter.vue';
export { default as UHotkey } from './UHotkey.vue';
export { default as UHover } from './UHover.vue';
export { default as UImg } from './UImg.vue';
export { default as UInfiniteScroll } from './UInfiniteScroll.vue';
export { default as UInput } from './UInput.vue';
export { default as UItem } from './UItem.vue';
export { default as UItemGroup } from './UItemGroup.vue';
export { default as UKbd } from './UKbd.vue';
export { default as ULabel } from './ULabel.vue';
export { default as ULayout } from './ULayout.vue';
export { default as ULazy } from './ULazy.vue';
export { default as UList } from './UList.vue';
export { default as UListGroup } from './UListGroup.vue';
export { default as UListItem } from './UListItem.vue';
export { default as UListItemSubtitle } from './UListItemSubtitle.vue';
export { default as UListItemTitle } from './UListItemTitle.vue';
export { default as UListSubheader } from './UListSubheader.vue';
export { default as ULocaleProvider } from './ULocaleProvider.vue';
export { default as UMain } from './UMain.vue';
export { default as UMessages } from './UMessages.vue';
export { default as UNavigationDrawer } from './UNavigationDrawer.vue';
export { default as UNoSsr } from './UNoSsr.vue';
export { default as UNumberInput } from './UNumberInput.vue';
export { default as UOtpInput } from './UOtpInput.vue';
export { default as UOverlay } from './UOverlay.vue';
export { default as UParallax } from './UParallax.vue';
export { default as UPicker } from './UPicker.vue';
export { default as UProgressCircular } from './UProgressCircular.vue';
export { default as UProgressLinear } from './UProgressLinear.vue';
export { default as UPullToRefresh } from './UPullToRefresh.vue';
export { default as URadioGroup } from './URadioGroup.vue';
export { default as URangeSlider } from './URangeSlider.vue';
export { default as URating } from './URating.vue';
export { default as UResponsive } from './UResponsive.vue';
export { default as USelectionControl } from './USelectionControl.vue';
export { default as USelectionControlGroup } from './USelectionControlGroup.vue';
export { default as USheet } from './USheet.vue';
export { default as USkeletonLoader } from './USkeletonLoader.vue';
export { default as USlideGroup } from './USlideGroup.vue';
export { default as USlideGroupItem } from './USlideGroupItem.vue';
export { default as USlider } from './USlider.vue';
export { default as USnackbar } from './USnackbar.vue';
export { default as USnackbarQueue } from './USnackbarQueue.vue';
export { default as USparkline } from './USparkline.vue';
export { default as USpeedDial } from './USpeedDial.vue';
export { default as UStepper } from './UStepper.vue';
export { default as UStepperActions } from './UStepperActions.vue';
export { default as UStepperItem } from './UStepperItem.vue';
export { default as UStepperVertical } from './UStepperVertical.vue';
export { default as UStepperWindow } from './UStepperWindow.vue';
export { default as UStepperWindowItem } from './UStepperWindowItem.vue';
export { default as USystemBar } from './USystemBar.vue';
export { default as UTimePicker } from './UTimePicker.vue';
export { default as UTimeline } from './UTimeline.vue';
export { default as UTimelineItem } from './UTimelineItem.vue';
export { default as UToolbar } from './UToolbar.vue';
export { default as UToolbarItems } from './UToolbarItems.vue';
export { default as UToolbarTitle } from './UToolbarTitle.vue';
export { default as UTransition } from './UTransition.vue';
export { default as UTreeview } from './UTreeview.vue';
export { default as UValidation } from './UValidation.vue';
export { default as UVirtualScroll } from './UVirtualScroll.vue';
export { default as UWindow } from './UWindow.vue';
export { default as UWindowItem } from './UWindowItem.vue';
export { typography } from './typography';
