// Existing UAH palette; keep these defaults aligned with tokens.css.
export const defaultUiThemes = {
    "light": {
        "dark": false,
        "colors": {
            "background": "#faf9f5",
            "sidebar": "#f0eee6",
            "surface": "#ffffff",
            "soft": "#f4f3ed",
            "hover": "#e9e7df",
            "selected": "#e4e1d8",
            "text": "#262624",
            "muted": "#66645e",
            "faint": "#77746b",
            "border": "#dedbd2",
            "line": "#e9e6de",
            "accent": "#a34f36",
            "accent-text": "#a34f36",
            "accent-soft": "#f3e7de",
            "green": "#47745c",
            "green-background": "#eaf1e8",
            "red": "#a9473e",
            "red-background": "#f8ebe6",
            "amber": "#896425",
            "amber-background": "#f6efdd",
            "usage-remaining": "#c1c8d0",
            "usage-category-1": "#918476",
            "usage-category-2": "#a7856c",
            "usage-category-3": "#bda78a",
            "usage-category-4": "#768b79",
            "usage-category-5": "#8b9b84",
            "usage-category-6": "#b9b7a0",
            "usage-category-7": "#bfa487",
            "usage-category-8": "#c5baa9",
            "code-keyword": "#7b3e91",
            "code-string": "#396949",
            "code-tag": "#965034",
            "code-number": "#a14e22",
            "code-comment": "#77746b",
            "code-property": "#315f8b",
            "scrollbar-thumb": "#66645e66",
            "scrollbar-thumb-hover": "#66645e99",
            "primary": "#a34f36",
            "primary-surface": "#a34f36",
            "secondary": "#66645e",
            "success": "#47745c",
            "error": "#a9473e",
            "warning": "#896425",
            "info": "#315f8b",
            "on-background": "#262624",
            "on-surface": "#262624"
        },
        "variables": {
            "shadow": "0 8px 35px #26262414, 0 1px 4px #26262409",
            "font": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Microsoft YaHei', 'Noto Sans CJK SC', sans-serif",
            "serif": "Georgia, 'Times New Roman', 'Noto Serif CJK SC', 'Songti SC', SimSun, serif",
            "mono": "'Cascadia Code', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
            "nav-width": "254px",
            "panel-width": "470px",
            "code-size": "13px",
            "motion-fast": "140ms",
            "motion-normal": "180ms",
            "motion-layout": "240ms",
            "ease": "cubic-bezier(.2, .7, .2, 1)"
        }
    },
    "dark": {
        "dark": true,
        "colors": {
            "background": "#262624",
            "sidebar": "#20201e",
            "surface": "#30302d",
            "soft": "#2d2d29",
            "hover": "#393933",
            "selected": "#414038",
            "text": "#f1f0e9",
            "muted": "#b2afa3",
            "faint": "#969388",
            "border": "#48473f",
            "line": "#3b3a34",
            "accent": "#a9563d",
            "accent-text": "#e6a086",
            "accent-soft": "#49362c",
            "green": "#a4c4a6",
            "green-background": "#2d3e32",
            "red": "#e5a69c",
            "red-background": "#472f2b",
            "amber": "#dfbf82",
            "amber-background": "#423b2b",
            "usage-remaining": "#555f6e",
            "usage-category-1": "#ad9b88",
            "usage-category-2": "#c39c7e",
            "usage-category-3": "#d6bd9b",
            "usage-category-4": "#8aa88e",
            "usage-category-5": "#a3b898",
            "usage-category-6": "#c6c4a9",
            "usage-category-7": "#d4b795",
            "usage-category-8": "#d2c5b1",
            "code-keyword": "#cfacf0",
            "code-string": "#b3d39e",
            "code-tag": "#edb194",
            "code-number": "#edbc7d",
            "code-comment": "#aaa597",
            "code-property": "#9dc5e6",
            "scrollbar-thumb": "#b2afa366",
            "scrollbar-thumb-hover": "#b2afa399",
            "primary": "#e6a086",
            "primary-surface": "#a9563d",
            "secondary": "#b2afa3",
            "success": "#a4c4a6",
            "error": "#e5a69c",
            "warning": "#dfbf82",
            "info": "#9dc5e6",
            "on-background": "#f1f0e9",
            "on-surface": "#f1f0e9"
        },
        "variables": {
            "shadow": "0 8px 35px #0004",
            "font": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Microsoft YaHei', 'Noto Sans CJK SC', sans-serif",
            "serif": "Georgia, 'Times New Roman', 'Noto Serif CJK SC', 'Songti SC', SimSun, serif",
            "mono": "'Cascadia Code', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
            "nav-width": "254px",
            "panel-width": "470px",
            "code-size": "13px",
            "motion-fast": "140ms",
            "motion-normal": "180ms",
            "motion-layout": "240ms",
            "ease": "cubic-bezier(.2, .7, .2, 1)"
        }
    }
};
