<script setup lang="ts">
import { createVNode, getCurrentInstance, onBeforeUnmount, onMounted, ref, render, watch } from 'vue';
import { createMarkdownDetailsMotion } from './markdownDetails';
import { patchMarkdownDom, sanitizedMarkdown } from './markdownDom';
import UiCodeBlock from './UiCodeBlock.vue';
import 'katex/dist/katex.min.css';

const props = defineProps<{ html: string; prefix: string }>();
const element = ref<HTMLElement>();
let version = 0;
let disposed = false;
const context = getCurrentInstance()?.appContext;
const codeRoots = new Set<HTMLElement>();
const reduced = () => document.documentElement.dataset.reducedMotion === 'true' || window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const detailsMotion = createMarkdownDetailsMotion();
let motionObserver: MutationObserver | undefined;
let motionMedia: MediaQueryList | undefined;
function settleMotion() { if (reduced()) detailsMotion.settle(); }
onMounted(() => {
    motionMedia = window.matchMedia('(prefers-reduced-motion: reduce)');
    motionMedia.addEventListener('change', settleMotion);
    motionObserver = new MutationObserver(settleMotion);
    motionObserver.observe(document.documentElement, { attributes: true, attributeFilter: ['data-reduced-motion'] });
});
watch([() => props.html, element], async () => {
    if (!element.value) return;
    const target = element.value;
    patchMarkdownDom(target, sanitizedMarkdown(props.html, props.prefix));
    codeRoots.forEach(root => { if (!target.contains(root)) { render(null, root); codeRoots.delete(root); } });
    target.querySelectorAll<HTMLElement>('[data-ui-code]').forEach(root => {
        const vnode = createVNode(UiCodeBlock, { code: root.dataset.uiCode || '', language: root.dataset.language || 'text' });
        vnode.appContext = context || null;
        render(vnode, root);
        root.setAttribute('data-code-rendered', '');
        codeRoots.add(root);
    });
    const current = ++version;
    const formulas = target.querySelectorAll<HTMLElement>('[data-ui-math]:not([data-math-rendered])');
    if (!formulas.length) return;
    const { default: katex } = await import('katex');
    if (disposed || current !== version) return;
    formulas.forEach(formula => {
        const source = formula.getAttribute('data-ui-math') || '';
        if (source.length > 10000) return;
        try {
            // Generated by KaTeX only, never model HTML. trust:false rejects
            // HTML, URLs and resource loading commands; bounds cap expansion.
            formula.innerHTML = katex.renderToString(source, { displayMode: formula.dataset.display === 'true', trust: false, strict: 'ignore', throwOnError: false, maxExpand: 1000, maxSize: 20, output: 'htmlAndMathml' });
            formula.setAttribute('data-math-rendered', '');
        } catch { /* Keep readable source for unsupported math. */ }
    });
}, { flush: 'post', immediate: true });
onBeforeUnmount(() => { disposed = true; version++; detailsMotion.dispose(); motionObserver?.disconnect(); motionMedia?.removeEventListener('change', settleMotion); codeRoots.forEach(root => render(null, root)); codeRoots.clear(); });
</script>

<template>
    <div ref="element" class="ui-markdown-content" @click="detailsMotion.click"></div>
</template>
