import { _electron as electron } from 'playwright';
import { createServer } from 'vite';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

await mkdir('artifacts', { recursive: true });
const evidence = await mkdtemp(path.resolve('artifacts/conversation-'));
const relative = path.relative(process.cwd(), evidence).replaceAll('\\', '/');
await writeFile(path.join(evidence, 'fixture.html'), `<!doctype html><html lang="zh"><head><meta charset="UTF-8"><title>Conversation prototype acceptance</title><style>body{margin:0}main{max-width:808px;margin:auto;padding:32px;box-sizing:border-box}</style></head><body><div id="app"></div><script type="module">
import { createApp, h, reactive } from 'vue';
import ConversationDemo from '/src/ui/docs/ConversationDemo.vue';
import UiDiff from '/src/ui/UiDiff.vue';
import UiActivity from '/src/ui/UiActivity.vue';
import '/src/ui/styles.css';
import '/src/docs-base.css';
const state = reactive({ example: 'conversation-inline', omitted: false, legacy: false });
window.fixture = { state };
createApp({ render: () => h('main', {}, state.omitted ? h(UiDiff, { compact: true, inspectable: true, path: 'large.txt', before: 'A'.repeat(310000), after: 'B'.repeat(310000) }) : state.legacy ? h(UiActivity, { title: '原有活动', status: '已完成', open: true }, () => '原有内容') : h(ConversationDemo, { example: state.example })) }).mount('#app');
</script></body></html>`, 'utf8');
const warnings = [];
const server = await createServer({ server: { host: '127.0.0.1', port: 0, watch: { ignored: ['**/artifacts/**'] } }, customLogger: { info() {}, warn(message) { warnings.push(message); }, warnOnce(message) { warnings.push(message); }, error(message) { throw new Error(message); }, clearScreen() {}, hasErrorLogged() { return false; }, hasWarned: false } });
await server.listen();
const env = { ...process.env, UAH_DATA_DIR: path.join(evidence, 'profile'), UAH_UI_PREVIEW_URL: server.resolvedUrls.local[0] + relative + '/fixture.html' };
delete env.ELECTRON_RUN_AS_NODE;
delete env.UAH_DEV_URL;
const app = await electron.launch({ args: ['tests/desktop/ui-host.cjs'], env });
try {
    const page = await app.firstWindow();
    page.setDefaultTimeout(12000);
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    const group = page.getByRole('button', { name: '使用了 3 个工具', exact: true });
    await group.waitFor();
    assert.equal(await group.getAttribute('aria-expanded'), 'true');
    await group.focus(); await page.keyboard.press('Enter');
    assert.equal(await group.getAttribute('aria-expanded'), 'false');
    await page.keyboard.press('Space');
    assert.equal(await group.getAttribute('aria-expanded'), 'true');
    const edit = page.getByRole('button', { name: '已编辑 ToolCallRow.ts +16 −2', exact: true });
    await edit.focus(); await page.keyboard.press('Enter');
    assert.equal(await edit.getAttribute('aria-expanded'), 'false');
    await page.keyboard.press('Space');
    assert.equal(await edit.getAttribute('aria-expanded'), 'true');
    await page.waitForTimeout(260);
    assert.equal(await page.locator('.ui-diff-toolbar, .ui-diff-counts').count(), 0);
    assert.equal(await page.locator('.ui-diff.is-compact [data-kind="added"]').count(), 2);
    assert.equal(await page.locator('.ui-diff.is-compact [data-kind="removed"]').count(), 1);
    assert.ok(await page.locator('.ui-activity.is-inline .ui-activity-body').evaluateAll(elements => elements.every(element => getComputedStyle(element).borderLeftWidth === '0px' && getComputedStyle(element).paddingLeft === '0px' && getComputedStyle(element).marginLeft === '0px')));
    const inspect = page.getByRole('button', { name: '在右栏查看', exact: true });
    await inspect.focus(); await page.keyboard.press('Enter');
    await page.getByRole('status').filter({ hasText: '在右栏查看：src/ui/ToolCallRow.ts' }).waitFor();
    const file = page.getByRole('button', { name: 'src/ui/ToolCallRow.ts M 增加 16 行，删除 2 行', exact: true });
    assert.equal(await file.getAttribute('title'), 'src/ui/ToolCallRow.ts');
    await file.focus(); await page.keyboard.press('Enter');
    await page.getByRole('status').filter({ hasText: '查看文件：tool' }).waitFor();
    await page.getByRole('button', { name: '查看全部', exact: true }).focus();
    await page.keyboard.press('Space');
    await page.getByRole('status').filter({ hasText: '查看全部文件改动' }).waitFor();
    assert.equal(await page.locator('.ui-message-actions button').count(), 5);
    assert.ok(await page.locator('.ui-message-actions button').evaluateAll(elements => elements.every(element => element.getBoundingClientRect().width === 28 && element.getBoundingClientRect().height === 28)));
    const actions = page.locator('.ui-message-actions');
    assert.equal(await actions.locator('.ui-tooltip-trigger[tabindex]').count(), 0);
    const copy = page.getByRole('button', { name: '复制回复', exact: true });
    await copy.focus();
    await page.getByRole('tooltip', { name: '复制回复', exact: true }).waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('tooltip', { name: '复制回复', exact: true }).isVisible(), false);
    await page.keyboard.press('Tab');
    assert.ok(await page.getByRole('button', { name: '编辑历史回复', exact: true }).evaluate(element => element === document.activeElement));
    await page.keyboard.press('Enter');
    await page.getByRole('status').filter({ hasText: '执行操作：edit' }).waitFor();
    await page.locator('h3').click();
    for (const [name, width, height, zoom] of [['light', 900, 1050, 1.25], ['dark', 900, 1050, 1.25], ['wide-light', 1440, 1080, 1], ['wide-dark', 1440, 1080, 1]]) {
        await page.evaluate(theme => document.documentElement.dataset.theme = theme, name.includes('dark') ? 'dark' : 'light');
        await app.evaluate(({ BrowserWindow }, dimensions) => { const window = BrowserWindow.getAllWindows()[0]; window.setSize(dimensions.width, dimensions.height); window.webContents.setZoomFactor(dimensions.zoom); }, { width, height, zoom });
        await page.waitForTimeout(400);
        const bounds = await page.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth, headers: Array.from(document.querySelectorAll('.ui-diff-header')).map(element => element.getBoundingClientRect().right) }));
        assert.ok(bounds.scroll <= bounds.width + 1, JSON.stringify(bounds));
        assert.ok(bounds.headers.every(right => right <= bounds.width + 1), JSON.stringify(bounds));
        const screenshot = await app.evaluate(async ({ BrowserWindow }) => (await BrowserWindow.getAllWindows()[0].capturePage()).toDataURL());
        await writeFile(path.join(evidence, name + '.png'), Buffer.from(screenshot.split(',')[1], 'base64'));
    }
    await page.evaluate(() => window.fixture.state.example = 'conversation-file-states');
    await page.getByText('统计不可用', { exact: true }).waitFor();
    assert.equal(await page.getByText('本轮无文件改动', { exact: true }).count(), 1);
    assert.equal(await page.locator('.ui-file-change-name').first().textContent(), 'an-extremely-long-file-name-with-unavailable-line-statistics.png');
    await page.evaluate(() => window.fixture.state.example = 'conversation-actions');
    const disabled = page.locator('.ui-message-actions').nth(1).getByRole('button', { name: '重新生成最新回复', exact: true });
    assert.equal(await disabled.isDisabled(), true);
    await page.evaluate(() => window.fixture.state.omitted = true);
    await page.getByText('此变更过大或计算复杂，未生成逐行预览。可复制完整快照查看。', { exact: true }).waitFor();
    assert.equal(await page.getByText('内容没有变化。', { exact: true }).count(), 0);
    await page.getByRole('button', { name: '复制新内容', exact: true }).click();
    assert.equal((await app.evaluate(({ clipboard }) => clipboard.readText())).length, 310000);
    await page.evaluate(() => { window.fixture.state.omitted = false; window.fixture.state.legacy = true; });
    await page.getByRole('button', { name: '原有活动 已完成', exact: true }).waitFor();
    assert.equal(await page.locator('.ui-activity.is-inline').count(), 0);
    assert.equal(await page.locator('.ui-activity-body').evaluate(element => getComputedStyle(element).borderLeftWidth), '1px');
    assert.deepEqual(errors, []);
    assert.equal(warnings.filter(warning => /cannot be child|hydration/i.test(warning)).length, 0);
    await writeFile(path.join(evidence, 'results.json'), JSON.stringify({ passed: true, assertions: ['nested inline tool group keyboard', 'no tool indentation/borders', 'compact diff accurate rows', 'inspect event', 'file path tooltip and select/view-all', 'message action tooltip keyboard and disabled state', 'theme and zoom screenshots', 'omitted diff full copy', 'legacy activity default preserved'], errors, warnings }, null, 4));
    console.log('PASS conversation prototype components: ' + evidence);
} finally { await app.close(); await server.close(); }
