import { _electron as electron } from 'playwright';
import { preview } from 'vite';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
await mkdir('artifacts',{recursive:true});
const evidence=await mkdtemp(path.resolve('artifacts/select-groups-'));
const server=await preview({build:{outDir:path.resolve('dist/docs')},preview:{host:'127.0.0.1',port:0,strictPort:false}});
const env={...process.env,UAH_DATA_DIR:path.join(evidence,'profile'),UAH_UI_PREVIEW_URL:server.resolvedUrls.local[0]+'index.html#/select'};
delete env.ELECTRON_RUN_AS_NODE;delete env.UAH_DEV_URL;
const app=await electron.launch({args:['tests/desktop/ui-host.cjs'],env});
try {
    const page=await app.firstWindow();
    const select=page.getByRole('combobox',{name:'分组模型',exact:true});
    page.setDefaultTimeout(8000);
    await select.click();
    await page.waitForTimeout(300);
    assert.equal(await select.locator('option[hidden]').isVisible(),false);
    assert.equal(await select.locator('optgroup').count(),2);
    const viewport=select.locator('.ui-scroll-viewport');
    assert(await viewport.evaluate(e=>e.scrollHeight>e.clientHeight));
    const thumb = await select.locator('.ui-scroll-thumb').boundingBox();
    assert(thumb);
    await page.mouse.move(thumb.x + thumb.width / 2, thumb.y + thumb.height / 2);
    await page.mouse.down();
    await page.mouse.move(thumb.x + thumb.width / 2, thumb.y + thumb.height / 2 + 60, { steps: 8 });
    await page.mouse.up();
    assert(await viewport.evaluate(e=>e.scrollTop>0));
    await viewport.evaluate(e=>e.scrollTop=400);
    await page.waitForTimeout(150);
    const capture=async name=>{ const data=await app.evaluate(async ({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toDataURL());await writeFile(path.join(evidence,name+'.png'),Buffer.from(data.split(',')[1],'base64')); };
    await capture('light');
    await viewport.evaluate(e=>e.scrollTop=0);
    await page.waitForTimeout(150);
    await capture('group-header');
    await select.locator('option').filter({hasText:'model-15'}).first().click();
    assert.equal(await select.inputValue(),'Provider A15');
    await select.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
    assert.notEqual(await select.inputValue(),'');
    await page.keyboard.press('Escape');
    await page.evaluate(()=>document.documentElement.dataset.theme='dark');
    await select.click();await page.waitForTimeout(200);await capture('dark');
    await page.keyboard.press('End');await page.keyboard.press('Enter');
    assert.equal(await select.inputValue(),'Provider B20');
    await page.keyboard.press('Escape');
    console.log('PASS '+evidence);
} finally {await app.close();await server.close();}
